#!/bin/sh -x

TEMPLATES=/home/stack/templates
STACK_NAME=$(hostname -s|cut -d- -f1)
mkdir -p ./logs
LOG_FILE=./logs/overcloud-deploy-${STACK_NAME}.$(date +%s).log

# openstack overcloud deploy \
time openstack overcloud deploy --templates ${TEMPLATES}/openstack-tripleo-heat-templates \
--stack ${STACK_NAME} \
--timeout 180 \
-e ${TEMPLATES}/overcloud_images.yaml \
-e ${TEMPLATES}/overcloud.yaml \
-e ${TEMPLATES}/network-environment.yaml \
-e ${TEMPLATES}/node-info.yaml \
-e ${TEMPLATES}/storage-environment.yaml \
-e ${TEMPLATES}/enable-tls.yaml \
-e ${TEMPLATES}/inject-trust-anchor.yaml \
-e ${TEMPLATES}/tls-endpoints-public-ip.yaml \
-e ${TEMPLATES}/firstboot-environment.yaml \
-e ${TEMPLATES}/nova-environment.yaml \
--ntp-server 192.168.8.4 2>&1 | tee $LOG_FILE
#--templates ./openstack-tripleo-heat-templates \
#-e /usr/share/openstack-tripleo-heat-templates/environments/network-isolation.yaml \

#-e ${TEMPLATES}/fencing.yaml \
#-e ${TEMPLATES}/post-config-environment.yaml \
ln -sf $LOG_FILE ./overcloud-deploy.log 
