resource_registry:
  OS::TripleO::Network::External: ./openstack-tripleo-heat-templates/network/external_v6.yaml
#  OS::TripleO::Network::External: ./openstack-tripleo-heat-templates/network/external.yaml
  OS::TripleO::Network::InternalApi: ./openstack-tripleo-heat-templates/network/internal_api.yaml
  OS::TripleO::Network::StorageMgmt: ./openstack-tripleo-heat-templates/network/storage_mgmt.yaml
  OS::TripleO::Network::Storage: ./openstack-tripleo-heat-templates/network/storage.yaml
  OS::TripleO::Network::Tenant: ./openstack-tripleo-heat-templates/network/tenant.yaml
#  OS::TripleO::Network::Management: ./openstack-tripleo-heat-templates/network/management.yaml

  # Port assignments for the VIPs
  #OS::TripleO::Network::Ports::NetVipMap: ./net_vip_map_external_v6.yaml
  OS::TripleO::Network::Ports::ExternalVipPort: ./openstack-tripleo-heat-templates/network/ports/external_v6.yaml
#  OS::TripleO::Network::Ports::ExternalVipPort: ./openstack-tripleo-heat-templates/network/ports/external.yaml
  OS::TripleO::Network::Ports::InternalApiVipPort: ./openstack-tripleo-heat-templates/network/ports/internal_api.yaml
  OS::TripleO::Network::Ports::StorageVipPort: ./openstack-tripleo-heat-templates/network/ports/storage.yaml
  OS::TripleO::Network::Ports::StorageMgmtVipPort: ./openstack-tripleo-heat-templates/network/ports/storage_mgmt.yaml 
  OS::TripleO::Network::Ports::TenantVipPort: ./openstack-tripleo-heat-templates/network/ports/tenant.yaml
#  OS::TripleO::Network::Ports::ManagementVipPort: ./openstack-tripleo-heat-templates/network/ports/management.yaml
#  OS::TripleO::Network::Ports::RedisVipPort: ./openstack-tripleo-heat-templates/network/ports/vip_v6.yaml
  OS::TripleO::Network::Ports::RedisVipPort: ./openstack-tripleo-heat-templates/network/ports/vip.yaml

  # Port assignments for the controller role
  OS::TripleO::Controller::Ports::ExternalPort: ./openstack-tripleo-heat-templates/network/ports/external_from_pool_v6.yaml
 # OS::TripleO::Controller::Ports::ExternalPort: ./openstack-tripleo-heat-templates/network/ports/external_from_pool.yaml
  OS::TripleO::Controller::Ports::InternalApiPort: ./openstack-tripleo-heat-templates/network/ports/internal_api_from_pool.yaml
  OS::TripleO::Controller::Ports::StoragePort: ./openstack-tripleo-heat-templates/network/ports/storage_from_pool.yaml
  OS::TripleO::Controller::Ports::TenantPort: ./openstack-tripleo-heat-templates/network/ports/tenant_from_pool.yaml
  OS::TripleO::Controller::Ports::StorageMgmtPort: ./openstack-tripleo-heat-templates/network/ports/storage_mgmt_from_pool.yaml
#  OS::TripleO::Controller::Ports::ManagementPort: ./openstack-tripleo-heat-templates/network/ports/management_from_pool.yaml

  # Port assignments for the compute role
  OS::TripleO::Compute::Ports::InternalApiPort: ./openstack-tripleo-heat-templates/network/ports/internal_api_from_pool.yaml
  OS::TripleO::Compute::Ports::StoragePort: ./openstack-tripleo-heat-templates/network/ports/storage_from_pool.yaml
  OS::TripleO::Compute::Ports::TenantPort: ./openstack-tripleo-heat-templates/network/ports/tenant_from_pool.yaml
  OS::TripleO::Compute::Ports::StorageMgmtPort: ./openstack-tripleo-heat-templates/network/ports/storage_mgmt_from_pool.yaml
#  OS::TripleO::Compute::Ports::ManagementPort: ./openstack-tripleo-heat-templates/network/ports/management_from_pool.yaml

  # Port assignments for the ceph storage role
  OS::TripleO::CephStorage::Ports::StoragePort: ./openstack-tripleo-heat-templates/network/ports/storage.yaml
  OS::TripleO::CephStorage::Ports::StorageMgmtPort: ./openstack-tripleo-heat-templates/network/ports/storage_mgmt.yaml

  # Port assignments for the swift storage role
  OS::TripleO::SwiftStorage::Ports::InternalApiPort: ./openstack-tripleo-heat-templates/network/ports/internal_api.yaml
  OS::TripleO::SwiftStorage::Ports::StoragePort: ./openstack-tripleo-heat-templates/network/ports/storage.yaml
  OS::TripleO::SwiftStorage::Ports::StorageMgmtPort: ./openstack-tripleo-heat-templates/network/ports/storage_mgmt.yaml

  # Port assignments for the block storage role
  OS::TripleO::BlockStorage::Ports::InternalApiPort: ./openstack-tripleo-heat-templates/network/ports/internal_api.yaml
  OS::TripleO::BlockStorage::Ports::StoragePort: ./openstack-tripleo-heat-templates/network/ports/storage.yaml
  OS::TripleO::BlockStorage::Ports::StorageMgmtPort: ./openstack-tripleo-heat-templates/network/ports/storage_mgmt.yaml

  # Node Net configuration
  OS::TripleO::BlockStorage::Net::SoftwareConfig: ./nic-configs/cinder-storage.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: ./nic-configs/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: ./nic-configs/controller-v6.yaml
#  OS::TripleO::Controller::Net::SoftwareConfig: ./nic-configs/controller.yaml
  OS::TripleO::ObjectStorage::Net::SoftwareConfig: ./nic-configs/swift-storage.yaml
  OS::TripleO::CephStorage::Net::SoftwareConfig: ./nic-configs/ceph-storage.yaml

  # First boot and Kernel Args
#  OS::TripleO::NodeUserData: first-boot.yaml

  OS::TripleO::Services::NeutronSriovAgent: openstack-tripleo-heat-templates/puppet/services/neutron-sriov-agent.yaml

parameter_defaults:
  InternalApiNetCidr: 192.168.12.0/23
  TenantNetCidr: 192.168.2.0/23
  StorageNetCidr: 192.168.0.0/24
  StorageMgmtNetCidr: 192.168.4.0/23
#  ManagementNetCidr: 172.16.6.0/23
#  ExternalNetCidr: '2600:5001:2830:30::/64'
  ExternalNetCidr: '2607:f160:f:f001::1/64'

  ExternalNetworkVlanID: 10
  InternalApiNetworkVlanID: 2804
  StorageNetworkVlanID: 222
  TenantNetworkVlanID: 970
  StorageMgmtNetworkVlanID: 971
#  ManagementNetworkVlanID: 406

  ExternalAllocationPools: [{'start': '2607:f160:f:f001:5::527', 'end': '2607:f160:f:f001:5::550'}]
#  ExternalAllocationPools: [{'start': '10.30.3.210', 'end': '10.30.3.220'}]
  InternalApiAllocationPools: [{'start': '192.168.12.4', 'end': '192.168.13.254'}]
  StorageAllocationPools: [{'start': '192.168.0.59', 'end': '192.168.0.65'}]
  TenantAllocationPools: [{'start': '192.168.2.4', 'end': '192.168.3.254'}]
  StorageMgmtAllocationPools: [{'start': '192.168.4.4', 'end': '192.168.5.254'}]
#  ManagementAllocationPools: [{'start': '172.16.6.111', 'end': '172.16.6.165'}]

  # Set to the router gateway on the external network
  ExternalInterfaceDefaultRoute: '2607:f160:f:f001::1'
#  ExternalInterfaceDefaultRoute: '10.30.2.1'
  # Gateway router for the provisioning network (or Undercloud IP)
#  InternalApiDefaultRoute: 172.16.2.17
  ControlPlaneDefaultRoute: 192.168.8.4
  ControlPlaneSubnetCidr: '23'
  # The IP address of the EC2 metadata server. Generally the IP of the Undercloud
  EC2MetadataIp: 192.168.8.4

  # Define the DNS servers (maximum 2) for the overcloud nodes
  # DnsServers: [","]
  DnsServers: ['8.8.8.8','8.8.4.4']

  # Set to "br-ex" if using floating IPs on native VLAN on bridge br-ex
  NeutronExternalNetworkBridge: "''"
  #NeutronNetworkType: vxlan
  NeutronNetworkType: 'vxlan,flat,vlan'
  NeutronTunnelTypes: vxlan
  NeutronGlobalPhysnetMtu: 1500
  NeutronFlatNetworks: ['datacentre','sriov_a','sriov_b']
  NeutronNetworkVLANRanges: ['datacentre','sriov_a','sriov_b']
  NeutronMechanismDrivers: ['openvswitch','sriovnicswitch']
  NeutronBridgeMappings: 'datacentre:br-ex'
  NeutronEnableIsolatedMetadata: 'True'

  # SRIO-V configuration
  NeutronSupportedPCIVendorDevs: ['8086:10ed']
  NeutronPhysicalDevMappings: ['sriov_a:ens1f0','sriov_b:ens1f1','sriov_a:ens2f0','sriov_b:ens2f1']
  NeutronSriovNumVFs: ['ens1f0:15','ens1f1:15','ens2f0:15','ens2f1:15']

  # Customize bonding options if required
  #BondInterfaceOvsOptions: "mode=1 miimon=100"
  BondInterfaceOvsOptions: "bond_mode=active-backup other_config:bond-detect-mode=miimon other_config:bond-miimon-interval=100"
  # BondInterfaceOvsOptions: "bond_mode=balance-slb lacp=off"
  # BondInterfaceOvsOptions: "bond_mode=balance-tcp lacp=active other-config:lacp-time=fast other-config:lacp-fallback-ab=true"
  # BondInterfaceOvsOptions: "bond_mode=balance-slb lacp=active other-config:lacp-time=fast other-config:lacp-fallback-ab=true"

  #  Old Settings
  ControlFixedIPs: [{'ip_address': '192.168.8.8'}]
#  PublicVirtualFixedIPs: [{'ip_address': '2600:5001:2830:30:0:0:13:11'}]
  PublicVirtualFixedIPs: [{'ip_address': '2607:f160:f:f001:5::515'}]

  NovaComputeIPs:
    internal_api:
    - 192.168.12.129
    - 192.168.12.130
    - 192.168.12.131
    - 192.168.12.132
    - 192.168.12.133
    - 192.168.12.134
    - 192.168.12.135
    - 192.168.12.136
    - 192.168.12.137
    - 192.168.12.138
    - 192.168.12.139
    - 192.168.12.140
    - 192.168.12.141
    - 192.168.12.142
    - 192.168.12.143
    - 192.168.12.144
    - 192.168.12.145
    - 192.168.12.146
    - 192.168.12.147
    - 192.168.12.148
    storage:
    - 192.168.0.21
    - 192.168.0.22
    - 192.168.0.23
    - 192.168.0.24
    - 192.168.0.25
    - 192.168.0.26
    - 192.168.0.27
    - 192.168.0.28
    - 192.168.0.29
    - 192.168.0.30
    - 192.168.0.31
    - 192.168.0.32
    - 192.168.0.33
    - 192.168.0.34
    - 192.168.0.35
    - 192.168.0.36
    - 192.168.0.37
    - 192.168.0.38
    - 192.168.0.39
    - 192.168.0.40
    tenant:
    - 192.168.2.129
    - 192.168.2.130
    - 192.168.2.131
    - 192.168.2.132
    - 192.168.2.133
    - 192.168.2.134
    - 192.168.2.135
    - 192.168.2.136
    - 192.168.2.137
    - 192.168.2.138
    - 192.168.2.139
    - 192.168.2.140
    - 192.168.2.141
    - 192.168.2.142
    - 192.168.2.143
    - 192.168.2.144
    - 192.168.2.145
    - 192.168.2.146
    - 192.168.2.147
    - 192.168.2.148
    storage_mgmt:
    - 192.168.4.129
    - 192.168.4.130
    - 192.168.4.131
    - 192.168.4.132
    - 192.168.4.133
    - 192.168.4.134
    - 192.168.4.135
    - 192.168.4.136
    - 192.168.4.137
    - 192.168.4.138
    - 192.168.4.139
    - 192.168.4.140
    - 192.168.4.141
    - 192.168.4.142
    - 192.168.4.143
    - 192.168.4.144
    - 192.168.4.145
    - 192.168.4.146
    - 192.168.4.147
    - 192.168.4.148
#    management:
#    - 172.16.6.15
#    - 172.16.6.16
    internal_api_cidr: '23'
    storage_cidr: '24'
    tenant_cidr: '23'
    storage_mgmt_cidr: '23'
#    management_cidr: '24'
  ControllerIPs:
  ControllerIPs:
    external:
    - 2607:f160:f:f001:5::501
    - 2607:f160:f:f001:5::502
    - 2607:f160:f:f001:5::503
    external_cidr: "64"
    externalv4:
    - 10.194.32.71
    - 10.194.32.72
    - 10.194.32.73
    externalv4cidr: "27"
    internal_api:
    - 192.168.12.7
    - 192.168.12.8
    - 192.168.12.9
    tenant:
    - 192.168.2.7
    - 192.168.2.8
    - 192.168.2.9
    storage:
    - 192.168.0.41
    - 192.168.0.42
    - 192.168.0.43
    storage_cidr: "23"
    tenant_cidr: "23"
    storage_mgmt:
    - 192.168.4.7
    - 192.168.4.8
    - 192.168.4.9
#    management:
#    - 172.16.6.12
#    - 172.16.6.13
#    - 172.16.6.14
    # CIDRs
    external_cidr: '64'
#    external_cidr: '23'
    internal_api_cidr: '23'
    storage_cidr: '24'
    tenant_cidr: '23'
    storage_mgmt_cidr: '23'
#    management_cidr: '24'

  # Enable IPv6 for Ceph.
  CephIPv6: False
  # Enable IPv6 for MongoDB. This is required when MongoDB is using an IPv6 IP.
  MongoDbIPv6: False
  # Enable various IPv6 features in Nova.
  NovaIPv6: False
  # Enable IPv6 for Corosync. This is required when Corosync is using an IPv6 IP in the cluster.
  CorosyncIPv6: False
  # Enable IPv6 environment for RabbitMQ.
  RabbitIPv6: False
  # Enable IPv6 in Glance.
  GlanceIPv6: False
  # Enable IPv6 in Memcached.
  MemcachedIPv6: False

  NetworkDeploymentActions: ['CREATE','UPDATE']
