#This file is an example of an environment file for defining the isolated
#networks and related parameters.
resource_registry:
  # Network Interface templates to use (these files must exist). You can
  # override these by including one of the net-*.yaml environment files,
  # such as net-bond-with-vlans.yaml, or modifying the list here.
  # Port assignments for the Controller
  OS::TripleO::Controller::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/controller.yaml
  # Port assignments for the Compute
  OS::TripleO::Compute::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/compute.yaml
  # Port assignments for the BlockStorage
  OS::TripleO::BlockStorage::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/cinder-storage.yaml
  # Port assignments for the ObjectStorage
  OS::TripleO::ObjectStorage::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/swift-storage.yaml
  # Port assignments for the CephStorage
  OS::TripleO::CephStorage::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/ceph-storage.yaml

parameter_defaults:
  # This section is where deployment-specific configuration is done
  # CIDR subnet mask length for provisioning network
  ControlPlaneSubnetCidr: '24'
  # Gateway router for the provisioning network (or Undercloud IP)
  ControlPlaneDefaultRoute: 192.168.24.254
  EC2MetadataIp: 192.168.24.1  # Generally the IP of the Undercloud
  # Customize the IP subnets to match the local environment
  StorageNetCidr: '172.50.3.0/24'
  StorageMgmtNetCidr: '172.50.5.0/24'
  InternalApiNetCidr: '172.50.2.0/24'
  TenantNetCidr: '172.50.4.0/24'
  ExternalNetCidr: ''
  ManagementNetCidr: '172.50.6.0/24'
  # Customize the VLAN IDs to match the local environment
  StorageNetworkVlanID: 503
  StorageMgmtNetworkVlanID: 505
  InternalApiNetworkVlanID: 502
  TenantNetworkVlanID: 504
  ExternalNetworkVlanID: 30
  ManagementNetworkVlanID: 506
  StorageAllocationPools: [{'start': '172.50.3.10', 'end': '172.16.1.250'}]
  StorageMgmtAllocationPools: [{'start': '172.50.5.10', 'end': '172.16.3.250'}]
  InternalApiAllocationPools: [{'start': '172.50.2.10', 'end': '172.16.2.250'}]
  TenantAllocationPools: [{'start': '172.50.4.10', 'end': '172.16.0.250'}]
  # Leave room if the external network is also used for floating IPs
  ExternalAllocationPools: 
  ManagementAllocationPools: [{'start': '172.50.6.10', 'end': '172.50.6.250'}]
  # Gateway routers for routable networks
  # Define the DNS servers (maximum 2) for the overcloud nodes
  DnsServers: ["8.8.8.8","8.8.4.4"]
  # List of Neutron network types for tenant networks (will be used in order)
  NeutronNetworkType: 'vxlan,vlan'
  # The tunnel type for the tenant network (vxlan or gre). Set to '' to disable tunneling.
  NeutronTunnelTypes: 'vxlan'
  # Neutron VLAN ranges per network, for example 'datacentre:1:499,tenant:500:1000':
  NeutronNetworkVLANRanges: 'datacentre:1:1000'
  # Customize bonding options, e.g. "mode=4 lacp_rate=1 updelay=1000 miimon=100"
  # for Linux bonds w/LACP, or "bond_mode=active-backup" for OVS active/backup.
  BondInterfaceOvsOptions: "bond_mode=active-backup"